In [2]:
import numpy as np
#create matrix
x=np.array([[2,4],[6,8]])
y=np.array([[4,6],[2,5]])
#matrix addition
a=x+y
#matrix substraction
b=x-y
#element-wise multiplication
c=x*y
#matrix multiplication
d=np.dot(x,y)
#matrix transpose
e=x.T
print("Addition :")
print(a)
print("Substraction :")
print(b)
print("Element-wise Multiplication :")
print(c)
print("Multiplication :")
print(d)
print("Transpose :")
print(e)

Addition :
[[ 6 10]
 [ 8 13]]
Substraction :
[[-2 -2]
 [ 4  3]]
Element-wise Multiplication :
[[ 8 24]
 [12 40]]
Multiplication :
[[16 32]
 [40 76]]
Transpose :
[[2 6]
 [4 8]]


In [3]:
#WITH SVD 

import numpy as np
#create a simple Matrix
a=np.array([[2,4,6],[1,3,5],[2,3,4]])
#perform SVD
U,S,VT=np.linalg.svd(a)
#Choose the number of components to keep(eg:2)
components=2
#Reconstruct the matrix with reduced dimensions
construct_a=np.dot(U[:,:components],np.dot(np.diag(S[:components]),VT[:components,:]))
print("Original matrix :")
print(a)
print("\nReconstructed Matrix(with reduced dimensions) :")
print(construct_a)

Original matrix :
[[2 4 6]
 [1 3 5]
 [2 3 4]]

Reconstructed Matrix(with reduced dimensions) :
[[2. 4. 6.]
 [1. 3. 5.]
 [2. 3. 4.]]
